spring.application.name=application1

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lyricsflow
spring.datasource.username=postgres
spring.datasource.password=1234

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CHAVE DA API DO GEMINI
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.api-key=${GENAI-API-KEY}
spring.ai.google.genai.chat.options.response-mime-type=application/json