@baseUrl = http://localhost:8080/tasks

### Listar todas as músicas do banco
GET {{baseUrl}}
Accept: application/json


### Buscar música nova -> consultar API
POST {{baseUrl}}/music
Content-Type: application/json

{
    "title": "Yellow",
    "artist": "Coldplay"
}


### Gerar tarefa
POST {{baseUrl}}/start
Content-Type: application/json

{
    "userId": 11,
    "songId": 2
}

### Enviar resposta
POST {{baseUrl}}/submit
Content-Type: application/json

{
    "taskId": 26,
    "userId": 10,
    "userAnswers": [
        "heaven",
        "easy",
        "sky",
        "people",
        "living",
        "countries",
        "hard",
        "peace",
        "dreamer",
        "hope",
        "join",
        "world"
    ]
}